name: Release
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: 'on'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release To Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Get Latest Version
        id: GetLatestVersion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: odinn1984/go-sensibo
      - name: Update Go Pkg Cache
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        run: cd && go get -v github.com/odinn1984/go-sensibo@${{ steps.GetLatestVersion.outputs.release }}
