name: Release
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release To Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Update Go Pkg Cache
        run: make update-pkg-cache
