name: Release To Github
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [gopkg-cache]

jobs:
  release:
    name: Update Go Pkg Cache
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: latestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: odinn1984
          repo: go-sensibo
          excludes: prerelease, draft
      - name: Update Go Pkg Cache
        shell: bash
        run: make update-pkg-cache VERSION=${{ steps.latestRelease.outputs.release }}
